services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MaikSchneider\TcaApiHeadless\:
    resource: '../Classes/*'

  _instanceof:
    MaikSchneider\TcaApiHeadless\Block\BlockSerializerInterface:
      tags: [ 'tca_api_headless.block_serializer' ]

  MaikSchneider\TcaApiHeadless\Block\BlockSerializerRegistry:
    public: true
    arguments:
      $serializers: !tagged_iterator tca_api_headless.block_serializer

  # Public for retrieval from the container in functional tests.
  MaikSchneider\TcaApiHeadless\Composition\PageComposer:
    public: true

  MaikSchneider\TcaApiHeadless\Navigation\NavigationBuilder:
    public: true
